### ISSUE TITLE
update to vault 0.5.2

### ISSUE THREAD

**Issue by kevinludwig** [sjourdan/docker-vault#8]
Vault 0.5.2 has a few features that are super useful to have, you may want to add them:

vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=123456

Which allows a docker-compose to easily set up a dev/test environment without additional scripting.

**Comment by sjourdan** [comment]
Thanks! @dennybaa did all the work on [this PR](https://github.com/sjourdan/docker-vault/pull/7) I just merged. 

docker builds are now tagged too (https://hub.docker.com/r/sjourdan/vault/tags/)
